<?xml version="1.0" encoding="utf-8"?><Database Class="VibrometerClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="channel">
    <Type Name="channel">
      <Column Name="channel_id" Member="id" Storage="_channel_id" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" CanBeNull="false" />
      <Column Name="sample_rate" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="wave_data">
    <Type Name="wave_data">
      <Column Name="id" AutoSync="OnInsert" Type="System.String" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="channel_id" Type="System.Int32" CanBeNull="false" />
      <Column Name="time" Type="System.DateTime" CanBeNull="false" />
      <Column Name="data" Type="System.Byte" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="trend_data">
    <Type Name="trend_data">
      <Column Name="id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="trend_id" Member="trendconfig_id" Storage="_trend_id" AutoSync="OnInsert" Type="System.Int32" CanBeNull="false" />
      <Column Name="time" Type="System.DateTime" CanBeNull="false" />
      <Column Name="value" Type="System.Single" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="TrendConfig">
    <Type Name="TrendConfig" IsInheritanceDefault="true">
      <Column Name="id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" CanBeNull="false" />
      <Type Name="PeakConfig">
        <Column Name="option" Type="System.String" CanBeNull="false" />
      </Type>
      <Type Name="RmsConfig">
        <Column Name="start_idx" Type="System.Int32" CanBeNull="false" />
        <Column Name="end_idx" Type="System.Int32" CanBeNull="false" />
      </Type>
    </Type>
  </Table>
</Database>